services:
  kittentts:
    build: .
    image: kittenml/kittentts:local
    volumes:
      - ./data:/data
      - ./.cache:/cache
    command: ["--help"]

  # Fast dev workflow: run from source without rebuilds
  kittentts-dev:
    image: python:3.10-slim
    working_dir: /work
    volumes:
      - ./:/work
      - ./data:/data
      - ./.cache:/cache
    environment:
      - HF_HOME=/cache/huggingface
      - XDG_CACHE_HOME=/cache
      - PYTHONPATH=/work
    entrypoint: ["bash", "-lc"]
    # Installs deps once into a container layer and runs the CLI from source
    command: >-
      "apt-get update && apt-get install -y --no-install-recommends libsndfile1 espeak-ng && \
       pip install --no-cache-dir -r requirements.txt && \
       python scripts/tts_cli.py --help"
